const kMoon = 'assets/images/moon.png';
const kDashboard = 'assets/images/dashboard.png';
const kLocation = 'assets/images/location.png';
const kPrayer = 'assets/images/prayer.png';
const kBookmark = 'assets/images/bookmark.png';
const kQuran = 'assets/images/quran.png';
const kLogo = 'assets/images/logo.png';
// ! SALAT TIME
const kFajr = 'assets/images/fajr.png';
const kDhur = 'assets/images/dhur.png';
const kAsr = 'assets/images/asr.png';
const kMaghrib = 'assets/images/maghrib.png';
const kIsha = 'assets/images/isha.png';
// ! Audio Image
const kAudioImage = 'assets/images/quranimage.png';
