import '../../../models/quran_model.dart';

const String kBookMarkBox = 'bookmark';

Map<int, QuranModel> quranMap = {
  1: QuranModel(arName: 'الفاتحة', frName: 'el fatiha'),
  2: QuranModel(arName: 'البقرة', frName: 'el bakarah'),
  3: QuranModel(arName: 'أل عمران', frName: 'al imran'),
  4: QuranModel(arName: 'النساء', frName: 'An nisa'),
  5: QuranModel(arName: 'المائدة', frName: 'Al maidah'),
  6: QuranModel(arName: 'الأنعام', frName: 'al anam'),
  7: QuranModel(arName: 'الأعراف', frName: 'al araf'),
  8: QuranModel(arName: 'الأنفال', frName: 'al anfal'),
  9: QuranModel(arName: 'التوبة', frName: 'al tawbah'),
  10: QuranModel(arName: 'يونس', frName: 'younous'),
  11: QuranModel(arName: 'هود', frName: 'houd'),
  12: QuranModel(arName: 'يوسف', frName: 'yousouf'),
  13: QuranModel(arName: 'الرعد', frName: 'ar rad'),
  14: QuranModel(arName: 'ابراهيم', frName: 'ibrahim'),
  15: QuranModel(arName: 'الحجر', frName: 'al hijr'),
  16: QuranModel(arName: 'النحل', frName: 'an nahl'),
  17: QuranModel(arName: 'الاسراء', frName: 'al isra'),
  18: QuranModel(arName: 'الكهف', frName: 'al kahf'),
  19: QuranModel(arName: 'مريم', frName: 'mariam'),
  20: QuranModel(arName: 'طه', frName: 'taha'),
  21: QuranModel(arName: 'الأنبياء', frName: 'al anbiya'),
  22: QuranModel(arName: 'الحج', frName: 'al hajj'),
  23: QuranModel(arName: 'المؤمنون', frName: 'al mouminoun'),
  24: QuranModel(arName: 'النور', frName: 'an nour'),
  25: QuranModel(arName: 'الفرقان', frName: 'al fourqan'),
  26: QuranModel(arName: 'الشعراء', frName: 'ach chouara'),
  27: QuranModel(arName: 'النمل', frName: 'an naml'),
  28: QuranModel(arName: 'القصص', frName: 'al qasas'),
  29: QuranModel(arName: 'العنكبوت', frName: 'al ankabout'),
  30: QuranModel(arName: 'الروم', frName: 'ar roum'),
  31: QuranModel(arName: 'لقمان', frName: 'louqman'),
  32: QuranModel(arName: 'السجدة', frName: 'as sajdah'),
  33: QuranModel(arName: 'الأحزاب', frName: 'al ahzab'),
  34: QuranModel(arName: 'سبأ', frName: 'saba'),
  35: QuranModel(arName: 'فاطير', frName: 'fatir'),
  36: QuranModel(arName: 'يس', frName: 'yasin'),
  37: QuranModel(arName: 'الصافات', frName: 'as saffat'),
  38: QuranModel(arName: 'ص', frName: 'sad'),
  39: QuranModel(arName: 'الزمر', frName: 'az zoumar'),
  40: QuranModel(arName: 'غافر', frName: 'ghafir'),
  41: QuranModel(arName: 'فصلت', frName: 'fussilat'),
  42: QuranModel(arName: 'الشورى', frName: 'ash shura'),
  43: QuranModel(arName: 'الزخرف', frName: 'az zukhruf'),
  44: QuranModel(arName: 'الدخان', frName: 'ad dukhan'),
  45: QuranModel(arName: 'الجاثية', frName: 'al jathiya'),
  46: QuranModel(arName: 'الأحقاف', frName: 'al ahqaf'),
  47: QuranModel(arName: 'محمد', frName: 'muhammad'),
  48: QuranModel(arName: 'الفتح', frName: 'al fath'),
  49: QuranModel(arName: 'الحجرات', frName: 'al hujraat'),
  50: QuranModel(arName: 'ق', frName: 'qaf'),
  51: QuranModel(arName: 'الذاريات', frName: 'adh dhariyat'),
  52: QuranModel(arName: 'الطور', frName: 'at tur'),
  53: QuranModel(arName: 'النجم', frName: 'an najm'),
  54: QuranModel(arName: 'القمر', frName: 'al qamar'),
  55: QuranModel(arName: 'الرحمان', frName: 'al rahman'),
  56: QuranModel(arName: 'الواقعة', frName: 'al waqia'),
  57: QuranModel(arName: 'الحديد', frName: 'al hadid'),
  58: QuranModel(arName: 'المجادلة', frName: 'al mujadala'),
  59: QuranModel(arName: 'الحشر', frName: 'al hashr'),
  60: QuranModel(arName: 'الممتحنة', frName: 'al mumtahina'),
  61: QuranModel(arName: 'الصف', frName: 'as saff'),
  62: QuranModel(arName: 'الجمعة', frName: 'al jumua'),
  63: QuranModel(arName: 'المنافقون', frName: 'al mounafiqqun'),
  64: QuranModel(arName: 'التغابن', frName: 'at taghaboun'),
  65: QuranModel(arName: 'الطلاق', frName: 'at talaq'),
  66: QuranModel(arName: 'التحريم', frName: 'at tahrim'),
  67: QuranModel(arName: 'الملك', frName: 'al moulk'),
  68: QuranModel(arName: 'القلم', frName: 'al qalam'),
  69: QuranModel(arName: 'الحاقة', frName: 'al haqqah'),
  70: QuranModel(arName: 'المعارج', frName: 'al maarij'),
  71: QuranModel(arName: 'نوح', frName: 'nouh'),
  72: QuranModel(arName: 'الجن', frName: 'al jinn'),
  73: QuranModel(arName: 'المزمل', frName: 'al mouzzammil'),
  74: QuranModel(arName: 'المدثر', frName: 'al mouddathir'),
  75: QuranModel(arName: 'القيامة', frName: 'al qiyamah'),
  76: QuranModel(arName: 'الانسان', frName: 'al insan'),
  77: QuranModel(arName: 'المرسلات', frName: 'al mourassalat'),
  78: QuranModel(arName: 'النبأ', frName: 'an nabaa'),
  79: QuranModel(arName: 'النازعات', frName: 'an naziat'),
  80: QuranModel(arName: 'عبس', frName: 'abassa'),
  81: QuranModel(arName: 'التكوير', frName: 'at takwir'),
  82: QuranModel(arName: 'الانفطار', frName: 'al infitar'),
  83: QuranModel(arName: 'المطففين', frName: 'al moutaffifoun'),
  84: QuranModel(arName: 'الانشقاق', frName: 'al inchiqaq'),
  85: QuranModel(arName: 'البروج', frName: 'al bouroujj'),
  86: QuranModel(arName: 'الطارق', frName: 'at tariq'),
  87: QuranModel(arName: 'الأعلى', frName: 'al ala'),
  88: QuranModel(arName: 'الغاشية', frName: 'al ghachiyah'),
  89: QuranModel(arName: 'الفجر', frName: 'al fajr'),
  90: QuranModel(arName: 'البلد', frName: 'al balad'),
  91: QuranModel(arName: 'الشمس', frName: 'ach chams'),
  92: QuranModel(arName: 'الليل', frName: 'al layl'),
  93: QuranModel(arName: 'الضحى', frName: 'ad douha'),
  94: QuranModel(arName: 'الشرح', frName: 'ach charh'),
  95: QuranModel(arName: 'التين', frName: 'at tin'),
  96: QuranModel(arName: 'العلق', frName: 'al alaq'),
  97: QuranModel(arName: 'القدر', frName: 'al qadr'),
  98: QuranModel(arName: 'البينة', frName: 'al bayyinah'),
  99: QuranModel(arName: 'الزلزلة', frName: 'al zalzala'),
  100: QuranModel(arName: 'العاديات', frName: 'al adiyat'),
  101: QuranModel(arName: 'القارعة', frName: 'al qariah'),
  102: QuranModel(arName: 'التكاثر', frName: 'at takathor'),
  103: QuranModel(arName: 'العصر', frName: 'al asr'),
  104: QuranModel(arName: 'الهمزة', frName: 'al houmazah'),
  105: QuranModel(arName: 'الفيل', frName: 'al fil'),
  106: QuranModel(arName: 'قريش', frName: 'quraish'),
  107: QuranModel(arName: 'الماعون', frName: 'al maoun'),
  108: QuranModel(arName: 'الكوثر', frName: 'al kawthar'),
  109: QuranModel(arName: 'الكافرون', frName: 'al kafiroun'),
  110: QuranModel(arName: 'النصر', frName: 'an nasr'),
  111: QuranModel(arName: 'المسد', frName: 'al massad'),
  112: QuranModel(arName: 'الاخلاص', frName: 'al ikhlas'),
  113: QuranModel(arName: 'الفلق', frName: 'al falaq'),
  114: QuranModel(arName: 'الناس', frName: 'an nas'),
};
